### PR TITLE
Added optional area path and iteration path

### PR DESCRIPTION
**Pull request by CloudSmithIra**
I've added the ability to put in an optional area path and iteration path for the work items being created. I've also updated the readme for it.

### CODE REVIEW

**Comment by danhellem** [comment]
@CloudSmithIra thanks for the PR. I am just picking this back up after being away from MSFT for 6 months. I made a ton of changes today but will cherry pick these and add them into a separate commit

**Comment by CloudSmithIra** [comment]
Awesome! And thanks for the early leg work on this. It really helps us out a ton.

**Comment by danhellem** [comment]
@CloudSmithIra I added area path but not iteration path. Iteration is not a good idea to put into the config because the latest iteration changes each sprint. Puting it in config would mean you would have to push the config change often. Will think about a better way.

Actually may end up deprecating this repo in place of using GitHub actions...stand by

**Comment by CloudSmithIra** [comment]
That all makes sense. We have a "catch all" iteration path for our backlog and then divvy them out over sprints to the current iteration, but not everyone works like that. Moving to GitHub actions would be amazing. Please let me know if there's an action coming and it's source repo, I'm happy to contribute/collaborate where I can.

**Comment by danhellem** [comment]
@CloudSmithIra 

https://github.com/danhellem/github-actions-issue-to-work-item

**Pull request closed without merging**
